spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.147.1.90:3306/BIZ_MSG_DEV?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: imc-dev
    password: humuson0722
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      minimum-idle: 10
      auto-commit: false
      connection-timeout: 60000
  jpa:
    # Show or not log for each sql query
    show-sql: false
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: none
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false